source "https://rubygems.org"

gem "awesome_print"
gem "ruby-progressbar"
gem "json", git: "https://github.com/flori/json"
gem "optimist"
gem "fileutils"
gem "paint"
gem "faraday"
gem "highline"
gem "docker-api"
